### ISSUE TITLE
Reg:jibri and next cloud

### ISSUE THREAD

**Issue by naveenbabusa** [switnet-ltd/quick-jibri-installer#11]
I have installed successfully and wanted to check where does jibri store the recordings and how do I access it in next cloud. I could not find my recordings in next cloud any configuration needed 

Lastly Grafana how do I set it up ? 

Pls guide

**Comment by Ark74** [comment]
Hi!,

If you installed Nextcloud with our _JRA via Nextcloud_ installer, we have found an issue in our .json file that has being fixed on the latest commit,

You might wanna try this,

```
curl -s https://raw.githubusercontent.com/switnet-ltd/quick-jibri-installer/master/files/jra-nc-app-ef.json > /tmp/jra.json
sudo -u www-data php /var/www/nextcloud/occ files_external:import /tmp/jra.json
sudo -u www-data php /var/www/nextcloud/occ files:scan --all
```

Then, your recordings should be found at "Jitsi Record" folder on your Nextcloud.

About grafana, all the components are asked if they are required to be installed, if you run the main installer, it will ask if you want grafana (as the other components)
https://github.com/switnet-ltd/quick-jibri-installer/blob/master/quick_jibri_installer.sh#L490

If for some reason you skiped it, you can install it later running: grafana.sh
And visit it at https://your-jitsi-domain.com/grafana/

Regards

**Comment by Ark74** [comment]
Let me know if yo have any further issue
Regards

**Comment by naveenbabusa** [comment]
> ```
> sudo -u www-data php /var/www/nextcloud/occ files:scan --all
> ```

I am not able to access my Next cloud after running this command. Not sure whats the issue the browser is not even able to access the site 

ERR_CONNECTION_TIMED_OUT

looks like the site config went for a toss. Any directions

**Comment by naveenbabusa** [comment]
Any way i need to uninstall this and install again ?
How do you roll back the changes

**Comment by naveenbabusa** [comment]
It says my connection to the site is also not secured. Seems to have rewritten the config any suggestions pls

**Comment by Ark74** [comment]
> It says my connection to the site is also not secured. Seems to have rewritten the config any suggestions pls

One thing is not related with the other.
Seems you did changes on nginx, not on nextcloud.

- Are you  sing a VPS?
- Have you restarted it recently?
- Is the domain pointing to the correct IP?
- Have you upgraded recently?

Once again, these instructions can't modify you webserver configuration.

```
curl -s https://raw.githubusercontent.com/switnet-ltd/quick-jibri-installer/master/files/jra-nc-app-ef.json > /tmp/jra.json
sudo -u www-data php /var/www/nextcloud/occ files_external:import /tmp/jra.json
sudo -u www-data php /var/www/nextcloud/occ files:scan --all
```

Take a closer look on your bash history, to trace all the changes that they were done.
My guess is that the IP don't match the server domain.
