### ISSUE TITLE
reg: Kubernetes

### ISSUE THREAD

**Issue by naveenbabusa** [switnet-ltd/quick-jibri-installer#12]
Sorry i did not knew how to reach you folks . This setup installer is a beauty and thanks for the same

I wanted to request your team to see if we could get the setup using kubernetes following a scalable architecture like the one in https://github.com/hpi-schul-cloud/jitsi-deployment . This would be helpful to add any new JVB and Scale very fast for large conferences . 

Any guidance on this would be helpful

Pls note this is not an issue but a request to the team

**Comment by Ark74** [comment]
Hi, we're glad you find it useful.

About kubernetes, we don't have plans for that any time soon, on the other hand you might wanna sponsor something like it or contribute such feature.

Regards, closing now.
