### ISSUE TITLE
Older Jitsi and Jibri Version

### ISSUE THREAD

**Issue by naveenbabusa** [switnet-ltd/quick-jibri-installer#14]
Hi 

After running the bash , i found that it installs a older version and we need to upgrade the version by Apt update. Some of the configurations goes for a toss . SO request to look at having the Jitsi newer version always picked up 

Also it is hanging for long for installing nextcloud. Database installation

Thanks
Naveen

**Comment by Ark74** [comment]
We use the stable repository.
By the way that apt works and since we don't target any specified version, it's not possible to install an "old version".

It will always install the latest version available at the time of installation.
Also use jitsi-updater.sh to update.
