### ISSUE TITLE
Lobby feature isn't working

### ISSUE THREAD

**Issue by timowevel1** [switnet-ltd/quick-jibri-installer#18]
Made a few installations on 5 different servers, on all the lobby feature is not working. You can activate the Lobby, but you dont see people trying to join

Prosody says: 
`Nov 13 09:25:50 portmanager	error	Failed to open server port 5347 on ::1, Cannot assign requested address
Nov 13 09:25:50 portmanager	error	Error binding encrypted port for https: No certificate present in SSL/TLS configuration for https port 5281
Nov 13 09:25:50 portmanager	error	Error binding encrypted port for https: No certificate present in SSL/TLS configuration for https port 5281
`

I found out that that can be ignored. 

Log says
`Nov 13 09:25:50 imeet.tech:muc_lobby_rooms	info	Lobby component loaded`

What is the reason? Please check it because the problem is in the installation, it doesnt work on many different systems

**Comment by Ark74** [comment]
What are your firewall rules?

**Comment by Ark74** [comment]
I've tried on one instance installed just yesterday.
And it's working fine, my guess is that your firewall is blocking a prosody port.

Temporary disable your current firewall rules, and try again.

Please check our wiki here for more firewall info,
https://github.com/switnet-ltd/quick-jibri-installer/wiki/Firewall

If something is missing we can add that up.

**Comment by timowevel1** [comment]
Mh, don't got a firewalll enabled (ufw status inactive). Enabled it for testing and added all ports, same result. The user can request to join but it doesn't show up to accept.

**Comment by Ark74** [comment]
Are you using secure rooms?

**Comment by timowevel1** [comment]
No, I dont. I didnt install any extras

**Comment by Ark74** [comment]
Ohh, that makes sense.
No auth method is almost never used, still deciding if dropping it since I'll like to introduce JWT in the future at some point.
Prosody gets automagically configured by Jitsi, maintaining 3 auth methods will be annoying.

**Comment by timowevel1** [comment]
So what you mean is that the Lobby feature isnt working becaus I dont got secure rooms enabled? Any way to enable it though without enabling auth methods? (the Jitsi instances are public instances, so we dont need auth methods but we need the lobby feature)

**Comment by Ark74** [comment]
Sorry, i guess I didn't explained myself correctly.

This installer configures prosody for secure rooms w/lobby, we didn't have the case for public rooms yet.

Can't give a ETA but I'll try to review this shortly

**Comment by timowevel1** [comment]
Thank you so much, this would be awesome!

**Comment by Ark74** [comment]
@timololipop could you check the latest changes on the unstable branch, meaning before run the installer use 

```
git checkout unstable
```

to test the latest changes, thanks.

**Comment by timowevel1** [comment]
Tried it, works now! Thank you!

**Comment by timowevel1** [comment]
Hey, could you tell me what you changed so I can apply it to an existing installation?

**Comment by Ark74** [comment]
In terms of ...?
I've been working lately on several features, you might wanna check the commits on unstable to see what you prefer to do once they reach stable.

**Comment by timowevel1** [comment]
In terms of enabling the lobby mode when you dont got those auth methods enabled like I mentioned. I have an existing installation, installed with your installer and now I want to enable the Lobby Mode without reinstalling the whole jitsi

**Comment by Ark74** [comment]
I'll try to document that on the wiki on a opening, 'til then please check the script behaviour.
