### ISSUE TITLE
How to use grafana

### ISSUE THREAD

**Issue by daxiondi** [switnet-ltd/quick-jibri-installer#19]
Is there a good tutorial on how to use grafana with jitsi?

Like this one
https://community.jitsi.org/t/how-to-to-setup-grafana-dashboards-to-monitor-jitsi-my-comprehensive-tutorial-for-the-beginner/38696/6

**Comment by Ark74** [comment]
To use or to install?

**Comment by daxiondi** [comment]
use

**Comment by Ark74** [comment]
Ohh, no sorry that is out of the scope of this repository.
Closing.

**Comment by daxiondi** [comment]
I just want to ask how it's better to use jitsi in grafana

**Comment by Ark74** [comment]
It depends on the needs of the user, you can set it to monitor specific data.
Jitsi will keep doing what jitsi does, it isn't aware of grafana at all, it only sends logs to a specific output and grafana plots that data based on your setup needs.

The script will install a popular dashboard, you can build your own, but that is again out of the scope of this repo, there is no way one dashboard will meet the need of everyone.
Jitsi community or grafana docs may be a good place to start, then start testing based on your needs.

Find what are your needs and stick to the path it takes you to learn that.

**Comment by daxiondi** [comment]
Thank
