### ISSUE TITLE
 No registration no live streaming

### ISSUE THREAD

**Issue by islanda23** [switnet-ltd/quick-jibri-installer#21]
Hello,
i ran the script.

Jitsi works correctly.

Recordings and live streaming no.

In the recordings I see the system but there is no audio and video.

Live streaming does not start.

Help me.

**Comment by Ark74** [comment]
Check that,

- your server have enough resources
- your firewall meet the recommendations on the wiki
- your vm/vps/server is loading the required audio driverss (use tools/test-jibri-env.sh)

Regards

**Comment by Ark74** [comment]
Did you find the issue?
