### ISSUE TITLE
JWT Token 

### ISSUE THREAD

**Issue by naveenbabusa** [switnet-ltd/quick-jibri-installer#25]
How do u set up and use JWT token for new installation.

**Comment by Ark74** [comment]
Just run the script and it will ask what auth method you want to use.
- None
- Local (Secure Rooms)
- JWT

You select the one you need and go on.
Be aware that you will need your user management system to manage and create the required tokes according to your needs.

We have done test creating tokens manually, and with RocketChat, in that case RocketChat managed the automatic token fabrication.

**Comment by naveenbabusa** [comment]
Ok . What is Local Secure rooms . Isit prosody enabled authentication or isit setting password for rooms

**Comment by Ark74** [comment]
Yes, _Secure Rooms_ is based on prosody, where manually adding password to the room will qualify as _None_.
