### ISSUE TITLE
Jibri Issue

### ISSUE THREAD

**Issue by yodaphone** [switnet-ltd/quick-jibri-installer#31]
Installed using the script on a VM. installation wen thro fine & site is up just fine

but i am unable to record or livestream the meeting

attaching the jibri log

the selenium driver is failing

```
2021-02-19 15:21:17.129 SEVERE: [50] org.jitsi.jibri.selenium.JibriSelenium.run() An error occurred while joining the call: org.openqa.selenium.WebDriverException: <unknown>: Failed to read the 'localStorage' property from 'Window': Acc>
  (Session info: chrome=88.0.4324.182)
  (Driver info: chromedriver=88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}),platform=Linux 5.8.0-43-generic x86_64) (WARNING: The server did not provide any stacktrace information)
```

[jibri-log.txt](https://github.com/switnet-ltd/quick-jibri-installer/files/6010986/jibri-log.txt)

Any ideas as to why? Could it be that chrome is failing due to lack of certificate authentication?

this is a plain vanilla install. attaching the install log as well

[qj-installer.log](https://github.com/switnet-ltd/quick-jibri-installer/files/6011014/qj-installer.log)

**Comment by Ark74** [comment]
Please run [tools/test-jibri-env.sh](https://github.com/switnet-ltd/quick-jibri-installer/blob/master/tools/test-jibri-env.sh)

And share the output.
Maybe we can see more specific info there.

**Comment by yodaphone** [comment]
> Please run [tools/test-jibri-env.sh](https://github.com/switnet-ltd/quick-jibri-installer/blob/master/tools/test-jibri-env.sh)
> 
> And share the output.
> Maybe we can see more specific info there.

```
########################################################################
                  Welcome to Jibri Environment Tester
########################################################################
                    by Software, IT & Networks Ltd


Checking for updates....

#1 -- Check repository --

This installation is using the "stable" repository.

#2 -- Check latest updates for jibri --

Jibri is installed, checking version:
jibri:all/stable 8.0-61-g99288dc-1 uptodate
Jibri is already up to date: ✔

#3 -- Check Google Chrome/driver software.  --

Google Chrome 88.0.4324.182
ChromeDriver 88.0.4324.96
Google Chrome is already up to date: ✔

Chromedriver version seems according to Google Chrome: ✔

#4 -- Test kernel modules --

Great!
Module snd-aloop found!

#5 -- Test .asoundrc file --

Seems to be using the latest asoundrc file available!

#6 -- Old or new config --

What config version is this using?

> This jibri seems to be running the lastest configuration already.

If you think there maybe an error on checking you current jibri configuration.
Please report this to https://github.com/switnet-ltd/quick-jibri-installer/issues


###########################
     Score: 6 out of 6
###########################


Jibri Test complete, thanks for testing.

```

**Comment by yodaphone** [comment]
please see this post

https://community.jitsi.org/t/failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document/67863/6?u=masteryoda

**Comment by Ark74** [comment]
Indeed, the other log didn't show anything weird either.

> https://community.jitsi.org/t/failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document/67863/6?u=masteryoda

Oh, that's new.
I think I need to add a new test to the list, wondering if that impact previous installations.
Have you confirmed that solves the issue?

**Comment by yodaphone** [comment]
yes, i added it to my jibri.conf right below 

`jibri {`

& it works

```
    chrome {
        // The flags which will be passed to chromium when launching
        flags = [
          "--use-fake-ui-for-media-stream",
          "--start-maximized",
          "--kiosk",
          "--enabled",
          "--disable-infobars",
          "--autoplay-policy=no-user-gesture-required"
          "--ignore-certificate-errors"
        ]
    }
```

**Comment by Ark74** [comment]
Nice, :+1: 
This must be something on the new update from chrome.
 I've checked some installations but even when upgraded chrome/driver they don't seem affected.

I'll add it to the configuration.
Thanks for sharing the result.

**Comment by yodaphone** [comment]
found the issue & the need to add chrome section in jibri.conf
