### ISSUE TITLE
Jibri SSH login password

### ISSUE THREAD

**Issue by timowevel1** [switnet-ltd/quick-jibri-installer#34]
Hello,

when I deploy an additional node, it wants me to login via SSH to the Main Node with the user "jbsync_......". Where is the password located which I have to enter?

Thanks

**Comment by Ark74** [comment]
Hey, I guess you found out, right?

**Comment by timowevel1** [comment]
Yes, found it, I was blind. 
Could this be an enhancement? I am using Cloudflare and it doesnt recognize my DNS entries, although Letsencrypt works fine with the Cloudflare proxy, so I commented out the mechanism where it checks the DNS settings. Maybe you could add such a support.

**Comment by timowevel1** [comment]
But another thing: I installed Nextcloud through the script, thanks for adding it. Wouldnt be a problem though.
You added the /var/jbrecord folder as external storage, but in my NC it's empty, see here:
https://prnt.sc/111oe9t
Although the folder is not empty:
https://prnt.sc/111oep2

Any ideas on that?

**Comment by timowevel1** [comment]
Probably a problem with the Ownership of the folder owned by the Jibri user, other folders are working. Any idea how to fix that?

**Comment by Ark74** [comment]
> so I commented out the mechanism where it checks the DNS settings.

I might avoid exiting, and only warn about it.

>  NC it's empty

Seems to be a redis issue

**Comment by Ark74** [comment]
> Probably a problem with the Ownership of the folder owned by the Jibri user, other folders are working. Any idea how to fix that?

Seems to be a cache issue.
Just try giving a bit of time, or maybe restart redis.

**Comment by timowevel1** [comment]
Gave it some time, works. Thanks!
