### ISSUE TITLE
Warning: apt-key output should not be parsed (stdout is not a terminal)

### ISSUE THREAD

**Issue by cyberspazio** [switnet-ltd/quick-jibri-installer#37]
Press any key to continue...
OS: Ubuntu 18.04.1 LTS
Good, this is a supported platform!
Verifying System Resources:
CPU Cores/Threads: OK (4)
Memory: OK (7977 MiB)
All requirements seems meet!

    - We hope you have a nice recording/streaming session

Add Prosody repo
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK

Add Jitsi repo

Warning: apt-key output should not be parsed (stdout is not a terminal)
OK

**Comment by Ark74** [comment]
You can omit the warning, maybe is not the best approach but is reliable enough to be used.
If you have some fix or suggestion, I'd welcome a PR.

Regards

**Comment by cyberspazio** [comment]
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
Errors were encountered while processing:
 jitsi-meet-web-config
 jitsi-meet
E: Sub-process /usr/bin/dpkg returned an error code (1)
Installing Chromedriver
Archive:  /tmp/chromedriver_linux64.zip
  inflating: /usr/local/bin/chromedriver

Check Google Software Working...

Google Chrome 89.0.4389.114
ChromeDriver 90.0.4430.24

**Comment by Ark74** [comment]
Ohh, then you have a clear error.
Do you think is it related to the keys not being imported correctly?

**Comment by cyberspazio** [comment]
Errors were encountered while processing:
 jitsi-meet-web-config
 jitsi-meet
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by cyberspazio** [comment]
![error2](https://user-images.githubusercontent.com/26858502/114620957-6ce22500-9cac-11eb-8e25-2fb258c9c2ff.jpg)
![Uploading error.jpg…]()

**Comment by cyberspazio** [comment]
root@eventitalia3:~/quick-jibri-installer# sudo apt-get -y install jitsi
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package jitsi

**Comment by Ark74** [comment]
Is this a fresh install?

Inside the directory, quick-jibri-installer please do,
```
git log
```
and share the output

**Comment by cyberspazio** [comment]
fresh install

commit 07227ac62ec2d92d31ddbcc4d206ea527d411f73 (origin/unstable)
Author: Ark74 <ark@switnet.org>
Date:   Tue Apr 13 12:28:43 2021 -0500

    Print remote password clearer

    move more into awk

commit 85ca93d94bafef7f1e34596b6cbf53396b5b95df
Merge: b8dd9e0 457623b
Author: Luis Guzman <Ark74@users.noreply.github.com>
Date:   Mon Apr 12 10:55:14 2021 -0500

    5.4.3

    - Improve add-jibri-node.sh variable check and logic.
    - Let continue over simple DNS failing.
    - Indenting change

commit 457623b6016701b9ef52b65d18480fc24b337108
Author: Ark74 <ark@switnet.org>
Date:   Sun Apr 11 22:32:55 2021 -0500

    Update indenting too.

commit 62854919641f54d8273cd59cb43be299d48d1374
Author: Ark74 <ark@switnet.org>
Date:   Sun Apr 11 22:06:27 2021 -0500

    Fix indenting too.

commit bbbe7d56cdc6d639a4ed833a68d77bf809900a93
Author: Ark74 <ark@switnet.org>
:...skipping...
commit 70f09310929b705ff363c52bddde25036c814c0b (HEAD -> master, origin/master, origin/HEAD)
Merge: 85ca93d 07227ac
Author: Luis Guzman <Ark74@users.noreply.github.com>
Date:   Tue Apr 13 12:42:51 2021 -0500

    5.4.4

    - Print remote password clearer

commit 07227ac62ec2d92d31ddbcc4d206ea527d411f73 (origin/unstable)
Author: Ark74 <ark@switnet.org>
Date:   Tue Apr 13 12:28:43 2021 -0500

    Print remote password clearer

    move more into awk

commit 85ca93d94bafef7f1e34596b6cbf53396b5b95df
Merge: b8dd9e0 457623b
Author: Luis Guzman <Ark74@users.noreply.github.com>
Date:   Mon Apr 12 10:55:14 2021 -0500

    5.4.3

    - Improve add-jibri-node.sh variable check and logic.
    - Let continue over simple DNS failing.
    - Indenting change

commit 457623b6016701b9ef52b65d18480fc24b337108
Author: Ark74 <ark@switnet.org>
Date:   Sun Apr 11 22:32:55 2021 -0500

    Update indenting too.

commit 62854919641f54d8273cd59cb43be299d48d1374
Author: Ark74 <ark@switnet.org>
Date:   Sun Apr 11 22:06:27 2021 -0500

    Fix indenting too.

**Comment by cyberspazio** [comment]
I can provide user and pass for cloud server access

I reboot the cloud server ...

**Comment by Ark74** [comment]
Let me run a quick install.
To check.

**Comment by cyberspazio** [comment]
6 months ago I had installed jitsi + jibri + nexcloud + grafana easily with the script, now it returns errors.
I also tried the 4.x version but even this doesn't work, maybe the deposits are exchanged

**Comment by Ark74** [comment]
Nope, i guess I introduced an error on the latest update, sorry about that.
Fixing it.

**Comment by Ark74** [comment]
This should be fixed on 76c29d2173fe26e80270c31d4afe3b5a518bd5fa
Pull the latest commit and try again on a clean server.
Cheers!

**Comment by cyberspazio** [comment]
I try...
