### ISSUE TITLE
error fullchain.pem

### ISSUE THREAD

**Issue by cyberspazio** [switnet-ltd/quick-jibri-installer#39]
Apr 14 01:13:41 eventitalia3 nginx[7549]: nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/eventitalia3.cyberspazio.net/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/eventitalia3.cyberspazio.net/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

**Comment by Ark74** [comment]
Check the log file  qj-installer.log look for the part with "http-01 challenge for ..." there you might see the error.
DNS is pointing to an IP (hopefully the right one), check your firewall.

You might want to use this article as a base,
https://github.com/switnet-ltd/quick-jibri-installer/wiki/Firewall

Please remember that you can request assisted installation with us, I'll be glad to send you a quote.
Cheers!

**Comment by cyberspazio** [comment]
:-)))))
Thank you!  Thank you!  now how do I regenerate certificates?

**Comment by Ark74** [comment]
Certs are generated via,
```
letsencrypt certonly --standalone --renew-by-default --agree-tos -d domain.com
```

Closing as it's not a script issue.
