### ISSUE TITLE
unable to register

### ISSUE THREAD

**Issue by cyberspazio** [switnet-ltd/quick-jibri-installer#40]
Performed new installation on new Ubuntu 18,  unable to register
 Log attached

[no-recording](https://user-images.githubusercontent.com/26858502/115108557-7a7c0100-9f71-11eb-9b7f-dc03198cc80e.jpg)
[log-jitsi-jibri.zip](https://github.com/switnet-ltd/quick-jibri-installer/files/6328946/log-jitsi-jibri.zip)

/ Log attached

OK, open the doors:
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 4443/tcp
sudo ufw allow 10000/udp
sudo ufw allow 5222/tcp
sudo ufw allow 5347/tcp
sudo ufw allow 22/tcp
sudo ufw enable

**Comment by cyberspazio** [comment]
root@eventitalia3:~/quick-jibri-installer/tools# sudo bash test-jibri-env.sh

########################################################################
                  Welcome to Jibri Environment Tester
########################################################################
                    by Software, IT & Networks Ltd


Checking for updates....

#1 -- Check repository --

This installation is using the "stable" repository.

#2 -- Check latest updates for jibri --

Jibri is installed, checking version:
jibri:all/stable 8.0-83-g204354d-1 uptodate
Jibri is already up to date: ✔

#3 -- Check Google Chrome/driver software.  --

Warning: No Google Chrome doesn't seem installed
ChromeDriver 90.0.4430.24

#4 -- Test kernel modules --

Great!
Module snd-aloop found!

#5 -- Test .asoundrc file --

Seems to be using the latest asoundrc file available!

#6 -- Old or new config --

What config version is this using?

> This jibri seems to be running the lastest configuration already. ✔

If you think there maybe an error on checking you current jibri configuration.
Please report this to https://github.com/switnet-ltd/quick-jibri-installer/issues


#6.1 -- Check for specific Chrome flag --


> Seems you have the "--ignore-certificate-errors" flag required for Chrome v88 and later. ✔

If you think there maybe an error on checking you current jibri configuration.
Please report this to https://github.com/switnet-ltd/quick-jibri-installer/issues


##############################
     Score: 5.1 out of 6.1
##############################


Jibri Test complete, thanks for testing.

root@eventitalia3:~/quick-jibri-installer/tools#

**Comment by cyberspazio** [comment]
SOLVED:

sudo nano /etc/apt/sources.list.d/google-chrome.list

Next, copy the following line and paste it into the google-chrome.list file.

deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

To save the file in Nano text editor, press Ctrl+O, then press Enter to confirm. Next, press CTRL+X to exit. After that, run the following command to download Google’s signing key.

wget https://dl.google.com/linux/linux_signing_key.pub

Then use apt-key to add it to your keyring so the package manager can verify the integrity of Google Chrome deb package.

sudo apt-key add linux_signing_key.pub

Now update package list and install the stable version of Google Chrome.

sudo apt update

sudo apt install google-chrome-stable

:-)

**Comment by Ark74** [comment]
How odd that it didn't got installed on the first place.
Good you sort it out. Cheers.
