### ISSUE TITLE
Nextcloud with issues

### ISSUE THREAD

**Issue by johnfelipe** [switnet-ltd/quick-jibri-installer#43]
I do all this steps:

	#sudo apt-get update
	sudo apt-get install ntp

	cal
	date

	git clone https://github.com/switnet-ltd/quick-jibri-installer

	cd quick-jibri-installer

	sudo bash quick_jibri_installer.sh

	########################################################################
						Welcome to Jitsi/Jibri Installer
	########################################################################
						by Software, IT & Networks Ltd

	Featuring:
	- Jibri Recording and YouTube Streaming
	- Jibri Recordings Access via Nextcloud
	- Jigasi Transcription (Advanced)
	- Customized brandless mode
	- Recurring changes updater

	Learn more about these at,
	Main repository: https://github.com/switnet-ltd/quick-jibri-installer
	Wiki and documentation: https://github.com/switnet-ltd/quick-jibri-installer/wiki

	Press any key to continue...

	enter

	OS: Ubuntu 18.04.5 LTS
	Good, this is a supported platform!
	Verifying System Resources:
	CPU Cores/Threads: OK (8)
	Memory: OK (16039 MiB)
	All requirements seems meet!

		- We hope you have a nice recording/streaming session

	Add Prosody repo
	Warning: apt-key output should not be parsed (stdout is not a terminal)
	OK

	Add Jitsi repo

	Warning: apt-key output should not be parsed (stdout is not a terminal)
	OK
	> Do you plan to use Let's Encrypt SSL certs?: (yes or no)
	yes
	We'll defaul to Let's Encrypt SSL certs.
	> Please set your domain (or subdmain) here: (e.g.: jitsi.domain.com)
	wegomeetings.online
	> Did you mean?: wegomeetings.online (yes or no)
	yes

	########################################################################
						Please Setup Your Installation
	########################################################################

	Set sysadmin email (this is a mandatory field):
	xxxx@gmail.com

	## Setting up Jitsi Meet language ##
	You can define the language, for a complete list of the supported languages

	See here:
	https://github.com/jitsi/jitsi-meet/blob/master/lang/languages.json

	Jitsi Meet web interface will be set to use such language.

	Please set your language (Press enter to default to 'en'):
	es
	We'll take a minute to localize some UI excerpts if you need.

	> Do you want to translate 'Participant' to your own language?
	Leave empty to use the default one (English):
	Participante
	> Do you want to translate 'me' to your own language?
	This must be a really small word to present one self.
	Some suggestions might be: yo (Spanish) | je (French) | ich (German)

	Leave empty to use the default one (English):
	yo
	> Do you want to drop support for unsecure protocols TLSv1.0/1.1 now: (yes or no)
	yes
	> Do you want to install customized "brandless mode"?: (yes or no)
	yes
	Brandless mode will be set.
	> Do you want to disable the Welcome page: (yes or no)
	no
	> Jitsi Meet Auth Method selection.

	1) Local
	2) JWT
	3) None
	Select the authentication method for your Jitsi Meet instance: 1

	  > Users are created manually using prosodyctl, only moderators can open a room or launch recording.

	> Do you want to setup Jibri Records Access via Nextcloud: (yes or no)
	( Please check requirements at: https://github.com/switnet-ltd/quick-jibri-installer )
	yes

	-- JRA via Nextcloud will be enabled.

	> Do you want to setup Jigasi Transcription: (yes or no)
	( Please check requirements at: https://github.com/switnet-ltd/quick-jibri-installer )
	no

	> Do you want to setup Grafana Dashboard: (yes or no)
	( Please check requirements at: https://github.com/switnet-ltd/quick-jibri-installer )
	-- Jigasi Transcription won't be enabled.
	yes

	########################################################################
					  Start Jitsi Framework configuration
	########################################################################

	-> Adding external module to list prosody users...

	Now you can check registered users with:
	prosodyctl mod_listusers

	Changing default language to: es
	Last file edition at:  Mon, 26 Apr 2021 16:24:29 -0300

	Dropping TLSv1/1.1 in favor of v1.3

	Disable "Blur my background" until new notice

	Set username for secure room moderator:
	xx
	Secure room moderator password:
	xxx

	########################################################################
					 Jibri Recordings Access via Nextcloud
	########################################################################
						by Software, IT & Networks Ltd

	Please enter the domain to use for Nextcloud:
	cloud.xxxx.online
	Nextcloud user: xxx
	Nextcloud user password: xxxx

	> Do you want to enable HSTS for this domain?: (yes or no)
	  Be aware this option apply mid-term effects on the domain, choose "no"
	  in case you don't know what you are doing. More at https://hstspreload.org/
	no

	# Add Grafana Dashboard

	Processing 11969: {"pluginId":"","title":"Jitsi Metrics","imported":true,"importedUri":"db/jitsi-metrics","importedUrl":"/grafana/d/mcfIHGrZz/jitsi-metrics","slug":"jitsi-metrics","dashboardId":1,"folderId":0,"importedRevision":1,"revision":1,"description":"","path":"","removed":false}

	Go check:

	(emphasis on the trailing "/") to review configuration and dashboards.

	User: xx
	Password: xxx

	Please save it somewhere safe.

	Press any key to continue...
	enter

	# Checking ALSA - Loopback module...
	snd-aloop
	modprobe: FATAL: Module snd-aloop not found in directory /lib/modules/4.15.0-140-generic

	#-----------------------------------------------------------------------
	# Your audio driver might not be able to load.
	# We'll check the state of this Jibri with our 'test-jibri-env.sh' tool.
	#-----------------------------------------------------------------------

	########################################################################
					  Welcome to Jibri Environment Tester
	########################################################################
						by Software, IT & Networks Ltd

	Checking for updates....

	#1 -- Check repository --

	This installation is using the "stable" repository.

	#2 -- Check latest updates for jibri --

	Jibri is installed, checking version:
	jibri:all/stable 8.0-83-g204354d-1 uptodate
	Jibri is already up to date: ✔

	#3 -- Check Google Chrome/driver software.  --

	Google Chrome 90.0.4430.93
	ChromeDriver 90.0.4430.24
	Google Chrome is already up to date: ✔

	Chromedriver version seems according to Google Chrome: ✔

	#4 -- Test kernel modules --

	Reading package lists...
	Building dependency tree...
	Reading state information...
	linux-image-generic-hwe-18.04 is already the newest version (5.4.0.72.80~18.04.65).
	The following packages were automatically installed and are no longer required:
	  python-pyicu python3-lib2to3
	Use 'sudo apt autoremove' to remove them.
	0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.

	No module snd_aloop detected. ✖ <== IMPORTANT!
	Current kernel: 4.15.0-140-generic

	If you just installed a new kernel, please try rebooting.
	For now wait 'til the end of the recommended kernel installation.
	# Check and Install HWE kernel if possible...

	#5 -- Test .asoundrc file --

	Seems to be using the latest asoundrc file available!

	#6 -- Old or new config --

	What config version is this using?

	> This jibri seems to be running the lastest configuration already. ✔

	If you think there maybe an error on checking you current jibri configuration.
	Please report this to https://github.com/switnet-ltd/quick-jibri-installer/issues

	#6.1 -- Check for specific Chrome flag --

	> Seems you have the "--ignore-certificate-errors" flag required for Chrome v88 and later. ✔

	If you think there maybe an error on checking you current jibri configuration.
	Please report this to https://github.com/switnet-ltd/quick-jibri-installer/issues

	##############################
		 Score: 5.1 out of 6.1
	##############################

	Jibri Test complete, thanks for testing.

	Press any key to continue...
	enter

	########################################################################
						Installation complete!!
			   for customized support: http://switnet.net
	########################################################################

	Reading package lists...
	Building dependency tree...
	Reading state information...
	The following packages will be REMOVED:
	  python-pyicu python3-lib2to3
	0 upgraded, 0 newly installed, 2 to remove and 10 not upgraded.
																   After this operation, 1832 kB disk space will be freed.
	(Reading database ... 133993 files and directories currently installed.)
	Removing python-pyicu (1.9.8-0ubuntu1) ...
	Removing python3-lib2to3 (3.6.9-1~18.04) ...
	Reading package lists...
	Building dependency tree...
	Reading state information...
	Rebooting in...
	1

And when put my subdomain for login to nextcloud instance show me this:

![SNAG-0408](https://user-images.githubusercontent.com/428820/116144185-a6019880-a6a1-11eb-8734-52df1b4005f8.png)

How solve this?

**Comment by Ark74** [comment]
Fixed by #44 
Please try again on the latest release.

Cheers.
