### ISSUE TITLE
Scale up Jibri

### ISSUE THREAD

**Issue by timowevel1** [switnet-ltd/quick-jibri-installer#49]
Hey,

would you stack multiple Jibri nodes on one Server?

**Comment by Ark74** [comment]
I would recommend against centralizing multiple jibris on one server, that is of course unless you have somewhat 64 cores, 128GB RAM server on a colocation with controled temperature.

Jibri is pretty resource intensive, now that it records at 1920x1080, the previous minimum requirements are no longer enough, making it very likely to fail if not sized correctly, thus not having a good meeting/recording experience.

Also as you have correctly stated, it is not a recommended/supported/documented way of scaling jibri by upstream developers, so the time debugging issues might increase with further development.

Based on that, I don't think we will take that path, but if someone eventually is willing to fund it or the upstream development roadmap changes, we can take a look at it when that time comes.

**Comment by timowevel1** [comment]
Alright, thank you.
