### ISSUE TITLE
403 forbidden on meet.domain.com

### ISSUE THREAD

**Issue by brimur** [switnet-ltd/quick-jibri-installer#5]
Hi, I have a meet server that was running fine but I was missing recordings so ran your installer against my meet server and now after the reboot I get 403 Forbidden when I go to https://meet.<myDomain>.com. Its a VM so am able to roll back to before the installer but before I do that I wanted to ask if you know what might be causing this permissions issue? I installed grafana as part of the install and I can get to http://meet.domain.com/grafana but not the main site

**Comment by Ark74** [comment]
Hi,
Don't run this installer on a manually installed system.
This installer makes aware itself of you installation customization and installs accordingly, I would suggest to install always on a clean OS and go from there.

Please also make sure to describe better your OS.
16.04 / 18.04 / 20.04
They all have different setups, which make them harder to set but that's another story.

**Comment by brimur** [comment]
Ok thanks, I will try a clean install
