### ISSUE TITLE
How can delete password for rooms creation?

### ISSUE THREAD

**Issue by johnfelipe** [switnet-ltd/quick-jibri-installer#52]
Hi dear pls tell me how can delete password rooms creator, pls tell me path and file for do this setting
Tnks a lot

**Comment by Ark74** [comment]
Could you be more specific?

What do you mean by "password rooms creator"?
Do you mean secure rooms, where you login using a user and password created by using prosodyctl?

**Comment by johnfelipe** [comment]
Yes that password created by using prosodyctl

**Comment by Ark74** [comment]
When on a clean install you can choose None as an authentication method.

If you already have chosen Local (secure rooms) then you can disable that by commenting the line shown below,

```
/etc/jitsi/jicofo/sip-communicator.properties
#org.jitsi.jicofo.auth.URL=XMPP:domain.example.com
```

Then restart jicofo, that should be it.

**Comment by johnfelipe** [comment]
witch command use for restart jicofo?

**Comment by Ark74** [comment]
Use,

```
systemctl restart jicofo
```

**Comment by Ark74** [comment]
Seems all went well

Feel free to reopen if you still get asked about authentication with these change.
Cheers.
