### ISSUE TITLE
URGENT REQUEST OF HELP!!: After installing quick-jobri-installer my Ubuntu 18.04 is freezed!!

### ISSUE THREAD

**Issue by raphael10-collab** [switnet-ltd/quick-jibri-installer#54]
After installing quick-jibri-installer , a second user (???) has been added, 
![IMG_20210520_125834](https://user-images.githubusercontent.com/70313067/118967844-7c1f5700-b96b-11eb-889b-44b3e44b0354.jpg)

and entering with the first user I'm not able to do anything in Ubuntu 18.04: I cannot even open a command-line window.

URGENT HELP NEEDED!!!!

THANKS TO YOUR BLOODY QUICK-JIBRI-INSTALLER I NEED TO RE-INSTALL UBUNTU SYSTEM.

THANK YOU)))))!!!

**Comment by Ark74** [comment]
As I have said on the DM, installing a server side platform on a user directed OS is a bad idea.

Hope you have a better experience next time.
