### ISSUE TITLE
Etherpad Docker addon how can review

### ISSUE THREAD

**Issue by johnfelipe** [switnet-ltd/quick-jibri-installer#57]
Hi dear, i install a new instance with you awsome script but can you tell me how can review Etherpad Docker addon
Tnks

**Comment by Ark74** [comment]
On the installer you get asked about installing it.

> Do you want to setup Docker Etherpad: (yes or no)"

Once you answer yes. it installs and configures it.

Just enter a room and on the additional tools you'll see 


![shared-document](https://user-images.githubusercontent.com/7444518/120360868-d951cb80-c2ce-11eb-8f5c-15855d42abb0.png)
