### ISSUE TITLE
local record without voice

### ISSUE THREAD

**Issue by johnfelipe** [switnet-ltd/quick-jibri-installer#58]
https://cloud.wegojitsit.eu/s/SZijmyAaeFTMGA5

I record in local and something happend because audio is not there, how can resolve that?

**Comment by Ark74** [comment]
Seems to be a local setup issue, something like mic, browser, etc.

May you check if you see something a like on previous installations, or with other browsers.
Cheers

**Comment by johnfelipe** [comment]
Is new installation
I will check in Firefox

**Comment by Ark74** [comment]
Please reopen if you keep finding this issue.

**Comment by johnfelipe** [comment]
New issue is about YouTube live, why with your version is down streaming?
