### ISSUE TITLE
load balancer in your script - request of feature

### ISSUE THREAD

**Issue by johnfelipe** [switnet-ltd/quick-jibri-installer#61]
https://help.clouding.io/hc/es/articles/360022206819-C%C3%B3mo-instalar-Jitsi-Meet-server-con-m%C3%BAltiples-nodos-Jitsi-Videobridge-con-balanceo-de-carga-en-Ubuntu-o-Debian?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo5MTkwNjIsInVzZXJfaWQiOjM4MjAyNzQ4ODgzNCwidGlja2V0X2lkIjo3MzI1OSwiY2hhbm5lbF9pZCI6NjMsInR5cGUiOiJTRUFSQ0giLCJleHAiOjE2MjYwMDA1NTR9.akKxPSV_OtKq8zhVaz3-ZOGubgo-pLBIZ7O8KspI2Oc

is possible put in your script something like load balanced
i know is possible add new nodes, but load balanced is good feature
tnks
stay alert
ping me with your feedback

**Comment by Ark74** [comment]
If interested in getting a quote for this development. please get in contact with us via email.
Thanks.

**Comment by johnfelipe** [comment]
really quote i havent for a moment, i only put may be in your roadmap, tnks
