### ISSUE TITLE
Logo jitsi

### ISSUE THREAD

**Issue by TAGHDOUTI** [switnet-ltd/quick-jibri-installer#62]
Hello

After installing the solution, I find a problem in the logo that does not appear, I want to change the jitsi logo to the company logo but I can't find it and therefore I don't know how to display it, for change it from images: / usr / share / jitsi-meet / images /

Thanks you

**Comment by Ark74** [comment]
Please read the our position on the matter:
https://github.com/switnet-ltd/quick-jibri-installer/wiki/Custom-brandless-mode

**Comment by Ark74** [comment]
In sum, we could either keep the original branding or remove it at all, custom branding work goes to the final user.

In case you want custom branding you might want to see what we do here:
https://github.com/switnet-ltd/quick-jibri-installer/blob/master/jm-bm.sh

Specially the DEFAULT_LOGO_URL field in the /etc/jitsi/meet/$(domain)-interface-config.js file
Cheers!

**Comment by TAGHDOUTI** [comment]
I understand sir thank you
I like change and the brandless mode

Just like I said before, I just want to know how to make the jitsi logo appear on the homepage again to modify it with our own company logo.
