### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by gprsm** [switnet-ltd/quick-jibri-installer#70]
Thank you for your very good project.
one question:
What is Grafana Dashboard? And how to access it. (It is assumed that we have activated Grafana Dashboard in script)
thanx

**Comment by gprsm** [comment]
i found:
http://$DOMAIN/grafana/

**Comment by Ark74** [comment]
Grafana is a statistics viewer/storage,in a sense a log monitor and the one template we use is the standard recommended template for jitsi data.
The installer will ask if you want grafana dashboard installed, if you answer yes, then it will install it and give you the details to login.
If you answer no, then it won't be installed, real simple.

**Comment by Ark74** [comment]
Please feel free to reopen in case you have any issue.
