### ISSUE TITLE
Websocket issues

### ISSUE THREAD

**Issue by timowevel1** [switnet-ltd/quick-jibri-installer#71]
Hey, how are you?

I am currently working on a project I made myself using Node and it uses lib jitsi meet and needs a websocket connection. When I start a meeting using the Videobridge installed on the same server where also the whole Jitsi is running I dont get any issues. When a conference is started with another videobridge I get the following error:

WebSocket connection to 'wss://mydomain.com/colibri-ws/default-id/blablabla/blabla?blaablapwd=blabla' failed.
[modules\RTC\BridgChannel.js] <WebSocket.e.onclose>: Channel closed: 1006

I also checked the related configs and you already configured it for the use for Websockets, so I dont know why it is failing.

I really appreciate your help, thank you.

**Comment by jasonjenssen** [comment]
netstat -tulpn | grep :9090 doesnt give me an output, so it seems like it isnt running on the videobridge node.

**Comment by timowevel1** [comment]
videobridge {
    http-servers {
        public {
            port = 9090
        }
    }
    websockets {
        enabled = true
        domain = "domainofmainnode.com:443"
        tls = true
    }

**Comment by Ark74** [comment]
Multiple videobridges are a WIP, they were going to be introduced with OCTO but that project didn't get any funding.
So they might need some work on it.

I'm open to review any PR, as for right now I can't review the subject myself.
Cheers!

**Comment by timowevel1** [comment]
So you say that it is not offically supported that external videobridges are reachable via websocket?
https://doc.librechurch.org/Wiki.jsp?page=AdminJitsi#section-AdminJitsi-SetupVideoNode
What do you think of that guide?

**Comment by Ark74** [comment]
> So you say that it is not offically supported that external videobridges are reachable via websocket?

No, I mean the installer itself.
Multiple jvb work, just need to setup things right.

> What do you think of that guide?

I think that is already done, you are looking for multiple jvb, I guess you'll have more luck at: [community.jitsi.org](https://community.jitsi.org) or the main documentation at github.

**Comment by timowevel1** [comment]
I used your installer to set the additional nodes up, but the error above is the one I am getting

**Comment by Ark74** [comment]
Yeah, as I said, the JVB nodes do connect, websocket are advanced connections that were a WIP of a bigger project that didn't go forward, so it stayed on the basic implementation.

**Comment by timowevel1** [comment]
So getting these errors are normal? No way to fix it?

**Comment by Ark74** [comment]
Feel free to send a PR to complete the websocket part.
Or contact me directly if you'll like a quote on the matter.

Cheers!
