### ISSUE TITLE
Turn TCP/UDP

### ISSUE THREAD

**Issue by timowevel1** [switnet-ltd/quick-jibri-installer#73]
Hey,

why is tcp disabled in the turn config but used in the prosody config?

Thanks!

**Comment by Ark74** [comment]
What line?

**Comment by timowevel1** [comment]
no-tcp in turnserver.conf
and using tcp on 5349 for turns in the prosody conf

{ type = "turns", host = "jitsidev.facilisglobal.com", port = 5349, transport = "tcp", secret = true, ttl = 86400, algorithm = "turn" }

**Comment by Ark74** [comment]
I mean in the installer.

IIRC we don't touch that line, that should come from the jitsi package configuration itself, if you have being updating from back in time, it might be possible at the time that part was not enabled, but recent versions do, <strike>sadly</strike> some files become static, so no further changes are applied, like ngxin conf, domain.com-config.js, etc. So the maintainer needs to update/fix those.

Please confirm.

**Comment by timowevel1** [comment]
Dont quite understand, what should I confirm? So I should just leave it as it is?

**Comment by Ark74** [comment]
> Dont quite understand, what should I confirm?

If we tainted that particular line of configuration with the installer.

>  So I should just leave it as it is?

That depends on what you try to accomplish, AFAICT that's the default installation value and it works for us, I see no reason to hard code it one way or another.

**Comment by timowevel1** [comment]
Okay then I will just leave it as it is, thank you!
