### ISSUE TITLE
Jibri doesnt transfer recordings

### ISSUE THREAD

**Issue by timowevel1** [switnet-ltd/quick-jibri-installer#76]
Hey!
Suddenly, Jibri stops sending recordings to the main server. Do you have an idea why? It just happens with the new install I made today, did something in Jitsi change?

rsync errors
rsync: failed to set times on "/var/jbrecord/.": Operation not permitted (1)
rsync: recv_generator: mkdir "/var/jbrecord/averagepeasantsdeviseseldom_2022-03-07-21-21-02" failed: Permission denied (13)
*** Skipping any contents from this failed directory ***
rsync: recv_generator: mkdir "/var/jbrecord/averagepeasantsdeviseseldom_2022-03-07-21-21-57" failed: Permission denied (13)
*** Skipping any contents from this failed directory ***

Thanks!

**Comment by Ark74** [comment]
Have you replicated the same error on a second installation?
seems to be a permissions error.

**Comment by timowevel1** [comment]
Yes indeed, I replicated it on two other machines, recordings dont get transfered anymore

**Comment by Ark74** [comment]
Right now we are a short in time, we'll review this as soon as we complete some priority projects.
Please don't hold your breath on it, or at least not now.

**Comment by timowevel1** [comment]
No worries, I fixed it by using scp instead, just wanted to tell you^^ Thanks
________________________________

**Comment by timowevel1** [comment]
@Ark74 I am just curious, do you have an idea why Jitsi uses two Jibris to record ONE meeting? I am autoscaling in aws, on bootup the nickname gets changed but it happens, that two or even three instances sometimes record the same meeting. Do you have an idea?

**Comment by Ark74** [comment]
It only uses one, it will try to connect to the one it responds first, if not it may go to the next node, you might want to look for a setting that might increase the wait time.
Seems like your nodes are taking the same amount to respond and is not fast enough to lock one up definitely for such meeting.

**Comment by timowevel1** [comment]
Yes indeed, thank you, I fixed it buy firing up chrome on startup.
