### ISSUE TITLE
Stop sending Recordings to Main Server

### ISSUE THREAD

**Issue by timowevel1** [switnet-ltd/quick-jibri-installer#77]
Hey!
Is there a possiblity to stop Jibri sending the recordings to the main server? Ive commented out the whole remote-jbsync script, but the recordings are still landing on the server. Any ideas on that?

Thanks.

**Comment by Ark74** [comment]
Why do you send a link to the code you are implementing, so we ca take a look?
Also you might want to request some customization service, that help maintaining this projects alive.

Cheers.

**Comment by timowevel1** [comment]
Oh no I dont try to implement anything, I just want to keep the recordings on the Jibri node where it was recorded and avoid it from getting moved to the Main Node :D

**Comment by timowevel1** [comment]
I just removed rsync, thanks.
