### ISSUE TITLE
Brandless 

### ISSUE THREAD

**Issue by naveenbabusa** [switnet-ltd/quick-jibri-installer#8]
What does brandless means and welcome Page if I say no what would come up

**Comment by Ark74** [comment]
Brandless means that.
It removes most if not all the Jitsi from the interface, and gives you a brandless enviroment.

If you disable the welcome page, when you visit the jitsi domain, let's say:
conference.mydomain.com

It will create a random room and redirect you there.
You might wanna try this on a VM.
