### ISSUE TITLE
Issue with Configuration

### ISSUE THREAD

**Issue by nightstryke** [switnet-ltd/quick-jibri-installer#84]
For some reason the quick installer doesn't allow for customization of Jitsi like changing the watermark, favicon, and background image on the index page of Jitsi-meet or any settings in the app.bundle.js or the interface_config.js or even the main config.js

Either I'm doing something wrong or the Quick Installer is flawed.

**Comment by Ark74** [comment]
Both interface_config.js and config.js are on /etc/jitsi/meet/
That is done to preserve changes when updates are applied, find the files there and make the according changes.

About the index page we don't modify nothing there, so you might want to double check your changes.
Regards.
