### ISSUE TITLE
I can't found recorder function in browers.

### ISSUE THREAD

**Issue by akong77** [switnet-ltd/quick-jibri-installer#89]
I have installed clean ubuntu server 20.04 and use v7.0 quick-jibri-installer to install jitsi and jibri.
It's installed done and reboot system.I open meet url.But I can't see recorder this function.
I installed have show some error.
How to check any error or fix it?

**Comment by Ark74** [comment]
> I have installed clean ubuntu server 20.04 and use v7.0 

Do you mean the latest commit 9ab18fc ?

**Comment by akong77** [comment]
I don't know what is this problem.I just run quick-jibri0install.sh and auto reboot it.It's can't see recorder function.
I post some error.

`########################################################################
                  Start Jitsi Framework configuration
########################################################################


**************************
Prosody was unable to find lua-unbound
This package can be obtained in the following ways:

  Debian/Ubuntu | sudo apt install lua-unbound
       luarocks | luarocks install luaunbound
         Source | https://www.zash.se/luaunbound.html

Old DNS resolver library will be used
More help can be found on our website, at https://prosody.im/doc/depends
**************************

The given hostname does not exist in the config

**************************
Prosody was unable to find lua-unbound
This package can be obtained in the following ways:

  Debian/Ubuntu | sudo apt install lua-unbound
       luarocks | luarocks install luaunbound
         Source | https://www.zash.se/luaunbound.html

Old DNS resolver library will be used
More help can be found on our website, at https://prosody.im/doc/depends
**************************

sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
Changing default language to: zhTW
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
Last file edition at:  Mon, 24 Oct 2022 01:56:03 +0000
No app configuration done to server file, please report to:
    -> https://github.com/switnet-ltd/quick-jibri-installer/issues

Dropping TLSv1/1.1
nsed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory
sed: can't read /etc/jitsi/meet/jaas-config.js: No such file or directory

# Checking /etc/jitsi/meet/jaas-config.js file for errors

Watch out!, there seems to be an issue on /etc/jitsi/meet/jaas-config.js line:
undefined
Most of the times this is due upstream changes, please report to
https://github.com/switnet-ltd/quick-jibri-installer/issues

Created symlink /etc/systemd/system/multi-user.target.wants/jibri.service → /etc/systemd/system/jibri.service.
Created symlink /etc/systemd/system/jibri.service.wants/jibri-xorg.service → /etc/systemd/system/jibri-xorg.service.
Created symlink /etc/systemd/system/jibri-icewm.service.wants/jibri-xorg.service → /etc/systemd/system/jibri-xorg.service.
Created symlink /etc/systemd/system/jibri.service.wants/jibri-icewm.service → /etc/systemd/system/jibri-icewm.service.

#--------------------------------------------------
# Starting LetsEncrypt configuration
#--------------------------------------------------

#Set and upgrade certbot PPA if posssible...

Certbot PPA is not available for focal just yet, it won't be installed...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Skipped user interaction because Certbot doesn't appear to be running in a terminal. You should probably include --non-interactive or --force-interactive on the command line.
Obtaining a new certificate
An unexpected error occurred:
The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "jaas": Domain name needs at least one dot
IMPORTANT NOTES:
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
Please see the logfiles in /var/log/letsencrypt for more details.
sed: can't read /etc/nginx/sites-available/jaas.conf: No such file or directory
sed: can't read /etc/nginx/sites-available/jaas.conf: No such file or directory
17 0 * * * "/opt/acmesh/.acme.sh"/acme.sh --cron --home "/opt/acmesh/.acme.sh" > /dev/null
@weekly certbot renew --nginx > /var/log/letsencrypt/renew.log 2>&1

---- Installing python3-certbot-nginx ----Selecting previously unselected package python3-pyparsing.
(Reading database ... 113127 files and directories currently installed.)
Preparing to unpack .../python3-pyparsing_2.4.6-1_all.deb ...
Unpacking python3-pyparsing (2.4.6-1) ...
Selecting previously unselected package python3-certbot-nginx.
Preparing to unpack .../python3-certbot-nginx_0.40.0-0ubuntu0.1_all.deb ...
Unpacking python3-certbot-nginx (0.40.0-0ubuntu0.1) ...
Setting up python3-pyparsing (2.4.6-1) ...
Setting up python3-certbot-nginx (0.40.0-0ubuntu0.1) ...

> Setting up custom interface_config.js according to best practices.No interface_config.js configuration done to server file, please report to:
    -> https://github.com/switnet-ltd/quick-jibri-installer/issues

# Checking ALSA - Loopback module...snd-aloop

#-----------------------------------------------------------------------
# Audio driver seems - OK.
#-----------------------------------------------------------------------

########################################################################
                    Installation complete!!
           for customized support: http://switnet.net
########################################################################`

**Comment by Ark74** [comment]
Oh! I see, seems there is an issue with the new integration of JaaS offered through the installer.
I'll take a look.

**Comment by akong77** [comment]
Thanks a lot.

**Comment by Ark74** [comment]
Please try again on a clean instance or you can use start-over.sh pulling the latest changes.
Cheers

**Comment by Ark74** [comment]
Fixed, please feel free to reopen if you keep finding the issue.

**Comment by akong77** [comment]
Hello,
I use latest version to install.It's install done but nginx failed start.I found it's can't found follow path.
/etc/letsencrypt/live/
I make sure letsencrypt will generate done.

`[Wed 26 Oct 2022 08:35:05 AM CST] Installing from online archive.
[Wed 26 Oct 2022 08:35:05 AM CST] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Wed 26 Oct 2022 08:35:06 AM CST] Extracting master.tar.gz
[Wed 26 Oct 2022 08:35:06 AM CST] It is recommended to install socat first.
[Wed 26 Oct 2022 08:35:06 AM CST] We use socat for standalone server if you use standalone mode.
[Wed 26 Oct 2022 08:35:06 AM CST] If you don't use standalone mode, just ignore this warning.
[Wed 26 Oct 2022 08:35:06 AM CST] Installing to /opt/acmesh/.acme.sh
[Wed 26 Oct 2022 08:35:06 AM CST] Installed to /opt/acmesh/.acme.sh/acme.sh
[Wed 26 Oct 2022 08:35:06 AM CST] No profile is found, you will need to go into /opt/acmesh/.acme.sh to use acme.sh
[Wed 26 Oct 2022 08:35:07 AM CST] Installing cron job
[Wed 26 Oct 2022 08:35:07 AM CST] Good, bash is found, so change the shebang to use bash as preferred.
[Wed 26 Oct 2022 08:35:07 AM CST] OK
[Wed 26 Oct 2022 08:35:07 AM CST] Install success!
[Wed 26 Oct 2022 08:35:08 AM CST] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Wed 26 Oct 2022 08:35:08 AM CST] Create account key ok.
[Wed 26 Oct 2022 08:35:08 AM CST] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Wed 26 Oct 2022 08:35:09 AM CST] Registered
[Wed 26 Oct 2022 08:35:09 AM CST] ACCOUNT_THUMBPRINT='cvu7sRJ8C9fTVrf1z1W3XcmhQ6M4n48wcFIpYoZelnM'
[Wed 26 Oct 2022 08:35:09 AM CST] Creating domain key
[Wed 26 Oct 2022 08:35:09 AM CST] The domain key is here: /opt/acmesh/.acme.sh/meet.linguitronics.com/meet.linguitronics.com.key
[Wed 26 Oct 2022 08:35:09 AM CST] Single domain='meet.linguitronics.com'
[Wed 26 Oct 2022 08:35:09 AM CST] Getting domain auth token for each domain
[Wed 26 Oct 2022 08:35:10 AM CST] Getting webroot for domain='meet.linguitronics.com'
[Wed 26 Oct 2022 08:35:10 AM CST] Verifying: meet.linguitronics.com
[Wed 26 Oct 2022 08:35:11 AM CST] Pending, The CA is processing your order, please just wait. (1/30)
[Wed 26 Oct 2022 08:35:14 AM CST] Success
[Wed 26 Oct 2022 08:35:14 AM CST] Verify finished, start to sign.
[Wed 26 Oct 2022 08:35:14 AM CST] Lets finalize the order.
[Wed 26 Oct 2022 08:35:14 AM CST] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/794641877/137969457697'
[Wed 26 Oct 2022 08:35:16 AM CST] Downloading cert.
[Wed 26 Oct 2022 08:35:16 AM CST] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/04ca5223b784e54037701cbfccfaffc3f0eb'
[Wed 26 Oct 2022 08:35:16 AM CST] Cert success.
-----BEGIN CERTIFICATE-----
MIIFMjCCBBqgAwIBAgISBMpSI7eE5UA3cBy/zPr/w/DrMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMjEwMjUyMzM1MTVaFw0yMzAxMjMyMzM1MTRaMCExHzAdBgNVBAMT
Fm1lZXQubGluZ3VpdHJvbmljcy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
ggEKAoIBAQC31yObAfQzi+VJr3GAjmbFTVQab27cjzPdNZV0uKaOeMSb/1dFPpN8
h1hGIGeGpQShbaWZK3zV3hRIbC4GbvIahI/12CpoQYzMQgVl1+X1Wp5aXfZ+1qhZ
ZGbBwCshbB4TEkYHMA24n/Zh1vl5ZyYFYiG2o6QWt2LsJ20vwmA5vVDFi+3qHi8O
jFEOUg7zLq+yg3blsDg+PgOdPAed9RFTtBwgkqEtZ30py1/gNAsqwY5ouLu5zXRB
8nLwYB0v5Nu6U6OLjb42ERdFqbOJQnYf0Qy9PsNSb2Ei32tzf0b9WLWVqyI/6Y36
O9O4W+YABTsQTB70/gGfuyUMo5FiRdK1AgMBAAGjggJRMIICTTAOBgNVHQ8BAf8E
BAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQC
MAAwHQYDVR0OBBYEFGVvZmLSPOjHw+F2JUEFgdxuUXwNMB8GA1UdIwQYMBaAFBQu
sxe3WFbLrlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYV
aHR0cDovL3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5s
ZW5jci5vcmcvMCEGA1UdEQQaMBiCFm1lZXQubGluZ3VpdHJvbmljcy5jb20wTAYD
VR0gBEUwQzAIBgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYa
aHR0cDovL2Nwcy5sZXRzZW5jcnlwdC5vcmcwggEEBgorBgEEAdZ5AgQCBIH1BIHy
APAAdgC3Pvsk35xNunXyOcW6WPRsXfxCz3qfNcSeHQmBJe20mQAAAYQRtvyzAAAE
AwBHMEUCIQCnT+FTx1JuWt2y5W7lrV7QBiohRBjhhE94DuekLZd7YAIgIQNjdZJ1
jqoh0idv1XID9kXuHfmx+QayaX2qlgKZaJgAdgB6MoxU2LcttiDqOOBSHumEFnAy
E4VNO9IrwTpXo1LrUgAAAYQRtvzYAAAEAwBHMEUCIEVHnog2WvgJKSCW1iqTxMaK
ZFNxqwZtOkwKwdY/JF04AiEA3i/e0ggrpHWJus7FhNxxeqMAmx79BCaVhc///INj
/pEwDQYJKoZIhvcNAQELBQADggEBABI+MWmlyZsqKMvKHakUivl3P47vLeDerVpN
6PIDojYqe7iOzDQxiiCL3c4bRvbfj77rsFa/IVNaDQF7Ciuqae87Gt3iLkxsrthr
Oh044LiTuZdSDGUPcrNOtZ5M1M/wG16e11hdH3D2hHEsZFMBEJdc3dC66102DKG1
cnqdDFLhIDE33weTsbbpCf0voFhtsXx09OqK7EdyyLdm3ws7o4Xz+JDGmuzJyGCA
xqxmvZNYDSvfZUmriiyxCXbDNk/Bju/NgYwtQAh+2oFI5+MWsA1Y6QFNJWvk7MjC
rBewf8Cmw6u3uzEnZ7kDcBAmp8ck6DQ+CDZK1TrEVd7d5rE7Rd8=
-----END CERTIFICATE-----
[Wed 26 Oct 2022 08:35:16 AM CST] Your cert is in: /opt/acmesh/.acme.sh/meet.linguitronics.com/meet.linguitronics.com.cer
[Wed 26 Oct 2022 08:35:16 AM CST] Your cert key is in: /opt/acmesh/.acme.sh/meet.linguitronics.com/meet.linguitronics.com.key
[Wed 26 Oct 2022 08:35:16 AM CST] The intermediate CA cert is in: /opt/acmesh/.acme.sh/meet.linguitronics.com/ca.cer
[Wed 26 Oct 2022 08:35:16 AM CST] And the full chain certs is there: /opt/acmesh/.acme.sh/meet.linguitronics.com/fullchain.cer
[Wed 26 Oct 2022 08:35:16 AM CST] Installing key to: /etc/jitsi/meet/meet.linguitronics.com.key
[Wed 26 Oct 2022 08:35:16 AM CST] Installing full chain to: /etc/jitsi/meet/meet.linguitronics.com.crt
[Wed 26 Oct 2022 08:35:16 AM CST] Run reload cmd: systemctl force-reload nginx.service && /usr/share/jitsi-meet/scripts/coturn-le-update.sh meet.linguitronics.com
[Wed 26 Oct 2022 08:35:16 AM CST] Reload success`

**Comment by Ark74** [comment]
This is not an issue with the latest version.
Please make sure you are using the latest one, and starting on a clean installation.
If you are using the same VPS/VM you can use the script start-over.sh to "start over" the installation process.
